//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrainedLock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ders
    {
        public Ders()
        {
            this.Sinif = new HashSet<Sinif>();
            this.Ogrenci = new HashSet<Ogrenci>();
        }
    
        public int DersId { get; set; }
        public string DersAdi { get; set; }
    
        public virtual ICollection<Sinif> Sinif { get; set; }
        public virtual ICollection<Ogrenci> Ogrenci { get; set; }
    }
}
